### ISSUE TITLE
can not  install component on OSX

### ISSUE THREAD

**Issue by shnode** [componentjs/component#622]
When I run `$ npm install -g component` or `$ npm install componentjs/component `, nothing happened, only a cursor keeps rotating on terminal.

Is there something wrong with my local npm configurations?

**Comment by timaschew** [comment]
can reproduce the same , but just with this error:
`Refusing to install component as a dependency of itself`

strange, I just fixed the repo and republished, now it works again: https://github.com/componentjs/component/commit/1faa7767ae9fd1247e25193639aa682511683ca8

**Comment by shnode** [comment]
I still don't know what happened, just let it rotate, and finally it installed successfully......maybe after u fixed it up.

But whatever, thanks for your reply.  I was really screwed up with this.

**Comment by netpoetica** [comment]
Can confirm I was able to install both ways with 1.0.2 - I also ran `npm install -g component@1.0.1` (the version you guys would have been having trouble with) and was not able to replicate. Wonder if npm might have been having trouble for a min?

**Comment by shnode** [comment]
At that time, I also installed `stylus` and `uglify-js` without a hitch. That's why I had the doubt about component.
